---

- name: Add group for activemq
  group:
    name: '{{ activemq_group }}'
    state: present

- name: Add user for activemq
  user:
    name: '{{ activemq_user }}'
    group: '{{ activemq_group }}'
    home: '{{ activemq_install_dir }}'
    createhome: no
    comment: 'ActiveMQ service user'
    state: present

- name: Create directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ activemq_user }}'
    group: '{{ activemq_group }}'
    mode: '{{ item.mode }}'
  with_items:
    - { path: '{{ activemq_install_dir }}', mode: '0775' }
    - { path: '{{ activemq_data_dir }}', mode: 'u=rwx,g=rx,o=x' }
    - { path: '{{ activemq_conf_dir }}', mode: '0775' }
    - { path: '{{ activemq_tmp_dir }}', mode: '0775' }
    - { path: '/var/log/{{ activemq_instance_name }}', mode: '0755' }

- name: Download and unarchive activemq
  unarchive:
    src:   '{{ activemq_download_url }}'
    dest:  '{{ activemq_install_dir }}'
    owner: '{{ activemq_user }}'
    group: '{{ activemq_user }}'
    extra_opts: ['--strip-components=1']
    copy: no
